language: node_js
node_js: stable

before_install: npm install -g hexo-cli
install: npm install

script:
  - hexo clean
  - hexo g
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Build"
  - git push --force https://github.com/bynbyn/hi.bynbyn.com master